name: aiimscycle
description: "Simplify staff transportation with our user-friendly cycle rental service. Staff can quickly browse and book cycles through the app, promoting eco-friendly commuting within the AIIMS campus."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.0
  dio: ^5.4.1
  flutter_bloc: ^8.1.4
  image_picker: ^1.0.7
  photo_view: ^0.15.0
  flutter_spinkit: ^5.2.0
  crypto: ^3.0.3
  fluttertoast: ^8.2.4
#  flutter_camera_qrcode_scanner: ^2.0.0
  flutter_screenutil: ^5.9.0
  logger: ^2.2.0
  flutter_dotenv: ^5.1.0
  pretty_dio_logger: ^1.3.1
  safe_device: ^1.1.6
  encrypt: ^5.0.3
  sqflite: ^2.3.3
  intl: ^0.20.1
  upgrader: ^11.3.1
  uuid: ^4.4.0
  connectivity_plus: ^6.0.3
  lottie: ^3.1.0
  simple_barcode_scanner: ^0.2.5
  cached_network_image: ^3.3.1
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:

  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/cycle/
    - assets/
  #   - images/a_dot_ham.jpeg
